USE TP_BD2

SELECT *
FROM dbo.Producto

insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (1,180000, 'HELADERA', 'Heladera Drean 264Lts', 'DREAM',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (2,200000, 'HELADERA', 'Heladera Drean con dispenser 359 Lts', 'DREAM',1)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (3,450000, 'HELADERA', 'Heladera no frost Whirlpool 480 lts', 'WHIRLPOOL',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (4,490000, 'HELADERA', 'Heladera no frost Samsung 396 lts.', 'SAMSUNG',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (5,160000, 'LAVARROPA', 'Lavarropas Drean Next 6.06 ECO 6 Kg', 'DREAM',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (6,210000, 'LAVARROPA', 'Lavarropas Drean Next 7.10 ECO 7 Kg', 'DREAM',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (7,180000, 'LAVARROPA', 'Lavarropas Automático Samsung 8 Kg', 'SAMSUNG',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (8,230000, 'COCINA', 'Cocina Whirlpool multigas 56 cm BLANCA', 'WHIRLPOOL',4)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (9,250000, 'COCINA', 'Cocina Whirlpool multigas 55 cm INOX', 'WHIRLPOOL',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (10,110000, 'COCINA', 'Cocina Escorial MASTER CLASSIC BCA 56 GN blanca', 'ESCORIAL',5)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (11,150000, 'COCINA', 'Cocina Escorial MASTER STYLE NEG 56 MG negra', 'ESCORIAL',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (12,180000, 'COCINA', 'Cocina Electrica Philco BCA 60CM', 'PHILCO',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (13,130000, 'TV', 'Smart TV Samsung 50" 4K', 'SAMSUNG',4)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (14,80000, 'TV', 'Smart TV Samsung 32"', 'SAMSUNG',5)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (15,180000, 'TV', 'Smart TV LG 50UQ8050PSB UHD 50'' negro', 'LG',2)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (16,160000, 'TV', 'Smart TV Philips 50" 4K', 'PHILIPS',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (17,85000, 'CALEFON', 'Calefón Escorial 14 lts. s/llama piloto blanco', 'ESCORIAL',4)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (18,100000, 'CALEFON', 'Calefón a gas Orbis 14 lts. 315BHO', 'ORBIS',3)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (19,140000, 'CALEFON', 'Calefón a gas Orbis Eurotrend digital 20 lts.', 'ORBIS',5)
insert into dbo.Producto (IDproducto, PRECIO, NOMBRE, DESCRIPCION, MARCA, STOCK)
values (20,120000, 'CALEFON', 'Calefón Universal 18 Lts gas natural', 'UNIVERSAL',5)