SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cliente](
	[DNI] [int] NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[APELLIDO] [varchar](100) NOT NULL,
	[DIRECCION] [varchar](100) NOT NULL,
	[TELEFONO] [int] NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Producto](
	[IDproducto] [int] NOT NULL,
	[PRECIO] [int] NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
	[MARCA] [varchar](100) NOT NULL,
	[STOCK] [int] NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[IDproducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Vendedor](
	[DNI] [varchar](10) NOT NULL,
	[IDvendedor] [int] NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[APELLIDO] [varchar](100) NOT NULL,
	[TELEFONO] [int] NULL,
 CONSTRAINT [PK_Vendedor_1] PRIMARY KEY CLUSTERED 
(
	[IDvendedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Venta](
	[NROfactura] [int] NOT NULL,
	[IDvendedor] [int] NOT NULL,
	[IDproducto] [int] NOT NULL,
	[DNIcliente] [int] NOT NULL,
	[PRECIO] [int] NULL,
	[CANTIDAD] [int] NULL,
 CONSTRAINT [PK_Venta] PRIMARY KEY CLUSTERED 
(
	[NROfactura] ASC,
	[IDvendedor] ASC,
	[IDproducto] ASC,
	[DNIcliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Venta]  WITH CHECK ADD  CONSTRAINT [FK_Venta_Cliente1] FOREIGN KEY([DNIcliente])
REFERENCES [dbo].[Cliente] ([DNI])
GO

ALTER TABLE [dbo].[Venta] CHECK CONSTRAINT [FK_Venta_Cliente1]
GO

ALTER TABLE [dbo].[Venta]  WITH CHECK ADD  CONSTRAINT [FK_Venta_Producto] FOREIGN KEY([IDproducto])
REFERENCES [dbo].[Producto] ([IDproducto])
GO

ALTER TABLE [dbo].[Venta] CHECK CONSTRAINT [FK_Venta_Producto]
GO

ALTER TABLE [dbo].[Venta]  WITH CHECK ADD  CONSTRAINT [FK_Venta_Vendedor] FOREIGN KEY([IDvendedor])
REFERENCES [dbo].[Vendedor] ([IDvendedor])
GO

ALTER TABLE [dbo].[Venta] CHECK CONSTRAINT [FK_Venta_Vendedor]
GO