USE Libros
GO

--A - BASICAS
--1)
SELECT
	L.TITULO, L.AUTOR 
FROM 
	LIBRO L
	WHERE L.TIPO='no'
	AND L.PRECIO_ORI > 21

--2)
SELECT
	L.TITULO,L.AUTOR
FROM
	LIBRO L
	WHERE L.TIPO='no'
	AND L.PRECIO_ORI > 21
	AND L.EDICION > 1985

--3)
SELECT
	L.AUTOR,L.EDICION
FROM 
	LIBRO L
	WHERE L.AUTOR LIKE 'L%'

--4)
SELECT
	L.AUTOR,L.EDICION
FROM 
	LIBRO L
	WHERE L.AUTOR LIKE '[^g]%'

--5)
SELECT
	L.AUTOR,L.PRECIO_ORI,L.EDICION
FROM 
	LIBRO L
	WHERE L.AUTOR LIKE '%rr%'

--6)
SELECT
	L.TITULO,L.EDICION
FROM 
	LIBRO L
	WHERE L.PRECIO_ORI NOT BETWEEN 12 AND 25

--7)
SELECT
	DISTINCT L.EDICION,L.TIPO
FROM
	LIBRO L
	ORDER BY L.EDICION

--8)
SELECT
	L.NRO_LIBRO,L.EDICION,L.TIPO,L.PRECIO_ORI,L.PRECIO_ACT, (L.PRECIO_ACT-L.PRECIO_ORI) AS Diferencia
FROM
	LIBRO L
	ORDER BY L.TIPO,L.PRECIO_ORI

--9)
SELECT
	L.NRO_LIBRO,L.EDICION,L.TIPO,L.PRECIO_ORI,L.PRECIO_ACT, (L.PRECIO_ACT-L.PRECIO_ORI) AS Diferencias
FROM
	LIBRO L
	WHERE L.TIPO='es'
	ORDER BY Diferencias

--10)
SELECT 
	L.NRO_LIBRO,L.PRECIO_ORI,L.EDICION
FROM 
	LIBRO L
	WHERE L.EDICION > 1985 AND (L.TIPO='no' OR L.PRECIO_ORI > 21)

--11)
SELECT
	L.TITULO,L.AUTOR
FROM 
	LIBRO L
	WHERE L.TIPO='no' OR L.PRECIO_ORI>21

--12)
SELECT
	L.TITULO,L.PRECIO_ORI
FROM 
	LIBRO L
	WHERE L.EDICION IN(1948, 1978, 1985)

--13)
SELECT
	L.TITULO,L.EDICION
FROM 
	LIBRO L
	WHERE L.PRECIO_ORI BETWEEN 12 AND 15

--14)
SELECT
	L.TITULO,L.PRECIO_ORI,L.EDICION
FROM 
	LIBRO L
	WHERE L.TITULO LIKE '%r%s%'

--15)
SELECT
	L.TITULO,L.PRECIO_ORI,L.EDICION
FROM 
	LIBRO L
	WHERE L.TITULO LIKE '_A%'

--16)
SELECT
	L.TITULO,L.EDICION
FROM 
	LIBRO L
	WHERE L.TIPO='no'
	ORDER BY L.EDICION

--17)
SELECT 
	L.NRO_LIBRO,L.EDICION,L.TIPO
FROM 
	LIBRO L
	WHERE L.PRECIO_ORI > 20
	ORDER BY L.EDICION DESC, L.NRO_LIBRO  

--18)
SELECT
	L.NRO_LIBRO,L.EDICION,L.TIPO,L.PRECIO_ORI,L.PRECIO_ACT, (L.PRECIO_ACT-L.PRECIO_ORI) Diferencia
FROM 
	LIBRO L
	WHERE (L.PRECIO_ACT-L.PRECIO_ORI) > 10

--19)
SELECT
	L.NRO_LIBRO,L.EDICION,L.TIPO,L.PRECIO_ORI,L.PRECIO_ACT, (L.PRECIO_ACT-L.PRECIO_ORI) Diferencia
FROM 
	LIBRO L
	WHERE (L.PRECIO_ACT-L.PRECIO_ORI) > 10
	ORDER BY Diferencia DESC