--D - Consultas en varias tablas – uso de join (inner join – left join – right join)
USE Libros

--1)
SELECT
	LI.TITULO,P.F_PREST,P.F_DEVOL
FROM 
	PRESTAMO P
	JOIN LIBRO LI
	ON P.NRO_LIBRO=LI.NRO_LIBRO

--2)
SELECT
	LI.NRO_LIBRO,LI.TITULO,P.F_PREST,P.F_DEVOL
FROM 
	PRESTAMO P
	JOIN LIBRO LI
	ON P.NRO_LIBRO=LI.NRO_LIBRO

--3)
SELECT
	L.NRO_LECTOR,L.NOMBRE,COUNT(P.NRO_LIBRO) CantidadPrestamos
FROM 
	LECTOR L
	JOIN PRESTAMO P
	ON L.NRO_LECTOR=P.NRO_LECTOR
	GROUP BY L.NRO_LECTOR, L.NOMBRE

--4)
SELECT
	L.NRO_LIBRO,L.TITULO,P.NRO_COPIA,COUNT(C.NRO_COPIA) CantPresCopia
FROM
	LIBRO L
	JOIN COPIAS C
	ON L.NRO_LIBRO=C.NRO_LIBRO
	RIGHT JOIN PRESTAMO P
	ON P.NRO_COPIA=C.NRO_COPIA
	GROUP BY L.NRO_LIBRO,L.TITULO,P.NRO_COPIA

--5)
SELECT
	L.NRO_LIBRO,L.TITULO,COUNT(P.NRO_COPIA) CantPresCopia
FROM
	LIBRO L
	JOIN PRESTAMO P
	ON L.NRO_LIBRO=P.NRO_LIBRO
	WHERE P.F_PREST>2012
	GROUP BY L.NRO_LIBRO,L.TITULO

--6)
SELECT
	L.NRO_LIBRO,L.TITULO,C.NRO_COPIA,COUNT(C.NRO_COPIA) CantPrestamosCopia
FROM
	LIBRO L
	JOIN PRESTAMO P
	ON L.NRO_LIBRO=P.NRO_LIBRO
	JOIN COPIAS C
	ON P.NRO_COPIA=C.NRO_COPIA
	GROUP BY L.NRO_LIBRO,L.TITULO,C.NRO_COPIA
	HAVING COUNT(C.NRO_COPIA) > 1

--7)
SELECT
	L.NRO_LIBRO,L.TITULO,C.NRO_COPIA,P.F_PREST
FROM
	LIBRO L
	FULL JOIN PRESTAMO P
	ON L.NRO_LIBRO=P.NRO_LIBRO
	FULL JOIN COPIAS C
	ON P.NRO_COPIA=C.NRO_COPIA
	GROUP BY L.NRO_LIBRO,L.TITULO,C.NRO_COPIA,P.F_PREST

--8)
SELECT
	LE.NRO_LECTOR,LE.NOMBRE,L.NRO_LIBRO,L.TITULO,TL.DESCTIPO,P.F_PREST
FROM
	LECTOR LE
	JOIN PRESTAMO P
	ON LE.NRO_LECTOR=P.NRO_LECTOR
	JOIN LIBRO L
	ON P.NRO_LIBRO=L.NRO_LIBRO
	JOIN TIPOLIBRO TL
	ON L.TIPO=TL.TIPO
	WHERE L.TIPO IN('no','cu') AND P.F_DEVOL IS NOT NULL
	GROUP BY LE.NRO_LECTOR,LE.NOMBRE,L.NRO_LIBRO,L.TITULO,TL.DESCTIPO,P.F_PREST

--9)
SELECT	
	L.TITULO,LE.NOMBRE
FROM 
	LIBRO L
	JOIN PRESTAMO P
	ON L.NRO_LIBRO=P.NRO_LIBRO
	JOIN LECTOR LE
	ON P.NRO_LECTOR=LE.NRO_LECTOR
	WHERE P.F_DEVOL IS NULL
	GROUP BY L.TITULO,LE.NOMBRE

--10)
SELECT
	L.NRO_LECTOR,L.NOMBRE,P.F_PREST
FROM
	LECTOR L
	JOIN PRESTAMO P
	ON L.NRO_LECTOR=P.NRO_LECTOR
	WHERE P.F_DEVOL IS NULL
	GROUP BY L.NRO_LECTOR,L.NOMBRE,P.F_PREST

--11)
SELECT
	L.NRO_LECTOR,L.NOMBRE,LI.NRO_LIBRO,LI.TITULO,P.F_PREST
FROM
	LECTOR L
	JOIN PRESTAMO P
	ON L.NRO_LECTOR=P.NRO_LECTOR
	JOIN LIBRO LI
	ON P.NRO_LIBRO=LI.NRO_LIBRO
	WHERE P.F_DEVOL IS NOT NULL
	GROUP BY L.NRO_LECTOR,L.NOMBRE,LI.NRO_LIBRO,LI.TITULO,P.F_PREST

--12)
SELECT
	L.NRO_LECTOR,L.NOMBRE,LI.NRO_LIBRO,LI.TITULO,P.F_PREST
FROM
	LECTOR L
	JOIN PRESTAMO P
	ON L.NRO_LECTOR=P.NRO_LECTOR
	JOIN LIBRO LI
	ON P.NRO_LIBRO=LI.NRO_LIBRO
	WHERE P.F_DEVOL IS NOT NULL AND LI.TIPO IN('no','cu')
	GROUP BY L.NRO_LECTOR,L.NOMBRE,LI.NRO_LIBRO,LI.TITULO,P.F_PREST

--13)
SELECT
	L.NRO_LECTOR,L.NOMBRE,P.F_PREST
FROM
	LECTOR L
	FULL JOIN PRESTAMO P
	ON L.NRO_LECTOR=P.NRO_LECTOR
	GROUP BY L.NRO_LECTOR,L.NOMBRE,P.F_PREST